@startuml
[*] --> Off

state Off {
  [*] --> Standby
  Standby --> On : Start
}
state On {
  [*] --> LowHeating
  LowHeating --> HighHeating : Increase
  HighHeating --> LowHeating : Decrease
}

Off --> On : TurnOn
On --> Off : TurnOff
@enduml
