@startuml
[*] --> Off

state Off {
  [*] --> Standby
  Standby --> On : Start
}
state On {
  [*] --> NotHeating
  Heating --> NotHeating : GoodTemperature
  NotHeating --> Heating : TooLowTemperature
}

Off --> On : TurnOn
On --> Off : TurnOff
@enduml
