@startuml

title Voir l'énergie produite

actor Responsable

activate Responsable
activate Application
participant Prédicteur

Responsable -> Application: Lancement de l'application

activate Prédicteur
Application --> Prédicteur: getProducedEnergy()
Prédicteur --> Application: energy

Application --> Responsable: L'application montre l'énergie produite

deactivate Prédicteur

@enduml

