@startuml

title Voir l'énergie produite

actor Responsable

activate Responsable
activate Application
participant API

Responsable -> Application: Lancement de l'application

activate API
Application --> API: getProducedEnergy()
API --> Application: energy

Application --> Responsable: L'application montre l'énergie produite

deactivate API

@enduml

