@startuml

title Programmation des ouvertures des clapets

actor Responsable

activate Responsable
activate Application
participant Firebase
participant Hardware

Responsable -> Application: Set un intervalle d'ouverture


activate Firebase
Application --> Firebase: setInterval(Intervalle: interval)
Firebase --> Hardware: setInterval(Intervalle: interval)
Hardware --> Firebase: Réponse positive
Firebase --> Application: Réponse positive

Application --> Application: L'application enregistre l'intervalle
Application --> Responsable: L'application montre l'intervalle validé

loop tant que la routine existe
    alt il est l'heure de la routine
        Hardware --> Hardware: openValves(false)
        Hardware --> Firebase: Notifie la fermeture
        Firebase --> Application: Notifie la fermeture
        Application --> Responsable: Voyant vert !!!
    else il n'est pas l'heure
        Hardware --> Hardware: openValves(true)
        Hardware --> Firebase: Notifie l'ouverture
        Firebase --> Application: Notifie l'ouverture
        Application --> Responsable: Voyant rouge !!!
    end
end

deactivate Firebase

@enduml

