@startuml

title Voir la température de la pièce et du chauffage

actor Utilisateur

activate Utilisateur
activate Chauffage

Utilisateur -> Chauffage: Appui sur bouton pour allumer l'écran

Chauffage --> Chauffage: L'écran affiche la température
Chauffage --> Utilisateur: Lecture de la température

Chauffage --> Chauffage: Il s'éteint au bout d'une minute

@enduml