@startuml

title Allumage à distance

actor Utilisateur

activate Utilisateur
activate Application
participant API

Utilisateur -> Application: Appui sur un bouton ON/OFF


activate API
alt éteindre le chauffage
    Application --> API: switch(boolean: status)
    API --> API: Ventilateurs éteints
    API --> Application: Réponse positive
    Application --> Utilisateur: Voyant rouge !!!

else allumer le chauffage à une certaine température
    Application --> API: setTemperature(double: temperature)

    loop tant qu'une routine n'est pas atteinte
        alt température inférieure
            API --> API: Ventilateurs allumés
            API --> Application: Réponse positive
            Application --> Utilisateur: Voyant vert !!!
        else température supérieure
            API --> API: Ventilateurs éteints
            API --> Application: Réponse positive
            Application --> Utilisateur: Voyant rouge !!!
        end
    end
end

deactivate API

@enduml

