@startuml

title Allumage manuel

actor Utilisateur

activate Utilisateur
activate Chauffage

Utilisateur -> Chauffage: Basculage du bouton ON/OFF
Chauffage -> Firebase: manualSwitch(boolean status)
Firebase -> Hardware: manualSwitch(boolean status)
Hardware -> Firebase: notifie l'allumage
Firebase -> Chauffage: notifie l'allumage

Chauffage --> Utilisateur: Voyant vert !!!

deactivate Firebase

@enduml

