@startuml

title Allumage par routine

actor Responsable

activate Responsable
activate Application
participant Firebase
participant Hardware

Responsable -> Application: Set un intervalle d'activité et une température


activate Firebase
Application --> Firebase: setRoutine(Intervalle: interval, double temperature)
Firebase --> Hardware: setRoutine(Intervalle: interval, double temperature)
Hardware --> Firebase: Réponse positive
Firebase --> Application: Réponse positive

Application --> Application: L'application enregistre la routine
Application --> Responsable: L'application montre la routine validée

loop tant que la routine existe
    alt il est l'heure de la routine
        alt température inférieure à la température voulue
            Hardware --> Hardware: setFans(true)
            Hardware --> Firebase: Notifie l'allumage
            Firebase --> Application: Notifie l'allumage
            Application --> Responsable: Voyant vert !!!
        else température supérieure à la température voulue
            Hardware --> Hardware: setFans(false)
            Hardware --> Firebase: Notifie l'éteignage
            Firebase --> Application: Notifie l'éteignage
            Application --> Responsable: Voyant rouge !!!
        end
    end
end

deactivate Firebase

@enduml

