@startuml
class Utilisateur{
  - id : Integer
  - email : String
  - hashPassword : String
  - nom : String
  - typeCompte : TypeCompte
  + connecter() : token
    + getProducedEnergy(): double
    + getPrediction(idChauffage: Integer): PredictionResult
    + sendCommand(command: Command): boolean
}
class Chauffage{
  - id : Integer
  - nom : String
  + getTemperature(): Double
  + setTemperature(temp: Double): void
  + getEtat(): Boolean
  + setEtat(etat: Boolean): void
  + getVitesseVentilateur(): Double
  + setVitesseVentilateur(vitesse: Double): void
  
  
}
class DonneesChauffageT{
  - id: Integer
  - ensoleillement: Double
  - humidite : Double
  - tempExterieur : Double
  - tempInterieur : Double
  - date : DateTime
  + getDataFromChauffage():void
  + getDataFromMeteo():void
}
class Oracle{
  - id : Integer
   - energie : Double
   + makePrediction() : Oracle
 
}
class Controler{

  - etat : Boolean
  - temperature : Double
  - vitesseVentilateur : Double
  + getTemperature() : Double 
  + setRoutine(interval: Intervalle, temperature: double): boolean
    + setInterval(interval: Intervalle): boolean
}

enum TypeCompte{
  ADMIN
  USER
}


Utilisateur- Chauffage: posseder
Utilisateur"*" - "*" Chauffage
(Utilisateur, Chauffage) .. Controler

Utilisateur-- TypeCompte
Chauffage"1"- "*"DonneesChauffageT : envoyer
DonneesChauffageT"*"- "1" Oracle : etre traiter


@enduml
